### ISSUE TITLE
IE Display Issue

### ISSUE THREAD

**Issue by Cbc2** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App#11]
In IE/Edge there are issues in app.js when setting element styles (lines 388-415):
element[0].style

This results in the document showing in three different iframes that are small / have scrollbars.
![ie readonly property issue](https://user-images.githubusercontent.com/480288/36852816-c5f77860-1d3a-11e8-9adc-690976fc2d74.png)

**Comment by AamirWaseem** [comment]
@Cbc2 

Thank you for sharing the details.

Please use "**.style.cssText =** " instead of "**.style =** " for all occurrences in "**/Content/App.js**". We have updated source code with same solution. You can also get latest version and tryout the fix.

**Comment by Cbc2** [comment]
No problem - thanks for the quick response!
