### ISSUE TITLE
Issue when rendering large Excel sheets

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App#23]
This issue was originally raised via forum topic:
[https://forum.groupdocs.com/t/problem-with-excel-file/5880](https://forum.groupdocs.com/t/problem-with-excel-file/5880)

When rendering Excel document with too many records in the sheet, the application keeps on processing and ends up with the exception "A generic error occurred in GDI+". The issue occurs in image-based rendering. The problematic document is provided in the forum topic.

**Comment by AamirWaseem** [comment]
Thanks for sharing, we will look into it for resolution and will plan accordingly.

**Comment by gboscolo** [comment]
Any news about this? thanks

**Comment by usman-aziz** [comment]
@gboscolo ,

Thanks for coming back to us.

I am afraid that your reported issue is not fixed yet. However, we shall check if we can provide you any progress updates in this regards. We appreciate your cooperation.

**Comment by usman-aziz** [comment]
@gboscolo ,

This issue has been fixed. Please [download/clone](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App) the updated version of the application.

**Comment by gboscolo** [comment]
Ok this now work fine thanks!
This is ok until the load of thumbnails starts.. is there a way to implement an "on demand load" also for the thumbnails, as done for the document with "page preload" settting?

Thanks

Gianluca

**Comment by usman-aziz** [comment]
@gboscolo ,

Thanks for your feedback.
>  is there a way to implement an "on demand load" also for the thumbnails, as done for the document with "page preload" settting?

Yes, you can implement it in the front end application in the same way that is used for the document pages. Please note that this is an open source application which is developed to demonstrate the working of GroupDocs.Viewer API, therefore, you can enhance or modify it as per your requirements. 

Regards
