### ISSUE TITLE
Images are not loaded in .msg files

### ISSUE THREAD

**Issue by AamirWaseem** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App#3]
Images are not loaded in .msg files

**Comment by usman-aziz** [comment]
@AamirWaseem ,
This issue is also mentioned in: [https://forum.groupdocs.com/t/modern-ui-email-doesnt-fill-the-browser/5826/6?u=usman.aziz](https://forum.groupdocs.com/t/modern-ui-email-doesnt-fill-the-browser/5826/6?u=usman.aziz).
